import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react';


export default function Home() {

  useEffect(() =>
  {        
      document.body.classList.add("bg-slate-50");
  });
  return (
    <div className="prose prose-xl prose-stone min-h-screen px-8 mx-auto antialiased font-sans font-['Poppins']">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:ital@0;1&display=swap"
      rel="stylesheet"
    />
      </Head>
      <main className="mt-4">
        <h1 className="text-center">
          Exeter<br/>Climate<br/>Cafe
        </h1>

        <p>Join us at the Exeter Phoenix cafe bar for coffee & cake to talk about how the climate and biodiversity crisis is affecting you. Find us on the far side of the cafe near the auditorium. We usually have two sofas and a table.</p>
        <p>
Share how you are feeling with like minded people in a friendly space. No booking required, just turn up. No cost except whatever drinks etc you would like to buy.</p>
      </main>

      <footer className="">
      </footer>
    </div>
  )
}
